#!/bin/bash -e
## Run Puppet locally using puppet apply
r10k deploy environment -p -c /etc/puppetlabs/r10k/r10k.yaml
## Log status of the r10k run
if [ $? -eq 0 ]
then
    /usr/bin/logger -i "r10k has run successfully" -t "puppet-run"
    exit 0
else
    /usr/bin/logger -i "r10k has ran into an error, please run r10k manually" -t "r10k deploy environment -p -c /etc/puppetlabs/r10k/r10k.yaml"
    exit 1
fi

puppet apply  /etc/puppetlabs/code/environments/production/manifests/site.pp 

## Log status of the Puppet run
if [ $? -eq 0 ]
then
    /usr/bin/logger -i "Puppet has run successfully" -t "puppet-run"
    exit 0
else
    /usr/bin/logger -i "Puppet has ran into an error, please run Puppet manually" -t "puppet-run"
    exit 1
fi
